# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23f756f599118f8421a00f866c311616668ed008fa80ba416ade838003a90297fb78afb7aaea9fd25434adbef3a91289ba784b267b5099f0636987e51ce28789

test:
  secret_key_base: 707c1621366c56b6408b0883f2b17cd974ec94d230c431f44a5f80d6b98399bd6cdb5b9fb11dde21f778c0ecac2cc80131e62d0ec7c6bad08092423eb66684c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
